export default [
  { "weight": 2, "message": "Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet"},
  { "weight": 6, "message": "tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit"}, 
  { "weight": 9, "message": "pede et risus. Quisque libero lacus, varius et, euismod et, commodo at, libero. Morbi"}, 
  { "weight": 13, "message": "Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam"}, 
  { "weight": 3, "message": "elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed"}, 
  { "weight": 0, "message": "nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit."}, 
  { "weight": 0, "message": "blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin"}, 
  { "weight": 1, "message": "Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend,"}, 
  { "weight": 15, "message": "dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc,"}, 
  { "weight": 1, "message": "lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum."}, 
  { "weight": 10, "message": "eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus."}, 
  { "weight": 3, "message": "Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis"}, 
  { "weight": 13, "message": "Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent"}, 
  { "weight": 1, "message": "nibh. Donec est mauris, rhoncus id, mollis nec, cursus a, enim."}, 
  { "weight": 6, "message": "euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit."}, 
  { "weight": 4, "message": "tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam"}, 
  { "weight": 15, "message": "fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem vitae odio sagittis semper. Nam"}, 
  { "weight": 14, "message": "et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque"}, 
  { "weight": 8, "message": "amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In"}, 
  { "weight": 5, "message": "enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus"}, 
  { "weight": 10, "message": "Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce"}, 
  { "weight": 5, "message": "Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet"}, 
  { "weight": 7, "message": "taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos."}, 
  { "weight": 2, "message": "semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed"}, 
  { "weight": 0, "message": "a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer"}, 
  { "weight": 10, "message": "elit elit fermentum risus, at fringilla purus mauris a nunc. In at"}, 
  { "weight": 0, "message": "nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc"}, 
  { "weight": 8, "message": "lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu,"}, 
  { "weight": 3, "message": "tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus."}, 
  { "weight": 1, "message": "Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque"}, 
  { "weight": 3, "message": "ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl."}, 
  { "weight": 3, "message": "Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit."}, 
  { "weight": 5, "message": "id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per"}, 
  { "weight": 13, "message": "vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus."}, 
  { "weight": 8, "message": "molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula."}, 
  { "weight": 13, "message": "Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna. Phasellus"}, 
  { "weight": 2, "message": "amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam adipiscing lacus. Ut nec urna et"}, 
  { "weight": 2, "message": "Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla"}, 
  { "weight": 12, "message": "nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec"}, 
  { "weight": 7, "message": "lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed"}, 
  { "weight": 11, "message": "Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat"}, 
  { "weight": 2, "message": "malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue"}, 
  { "weight": 6, "message": "nunc, ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut,"}, 
  { "weight": 0, "message": "aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos."}, 
  { "weight": 14, "message": "tortor, dictum eu, placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer"}, 
  { "weight": 2, "message": "rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque"}, 
  { "weight": 15, "message": "Donec tincidunt. Donec vitae erat vel pede blandit congue. In scelerisque scelerisque dui. Suspendisse ac"}, 
  { "weight": 2, "message": "eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien."}, 
  { "weight": 13, "message": "et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu."}, 
  { "weight": 3, "message": "eget mollis lectus pede et risus. Quisque libero lacus, varius et, euismod et,"}, 
  { "weight": 12, "message": "Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius."}, 
  { "weight": 10, "message": "urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet"}, 
  { "weight": 1, "message": "lectus convallis est, vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus"}, 
  { "weight": 15, "message": "penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean"}, 
  { "weight": 4, "message": "luctus aliquet odio. Etiam ligula tortor, dictum eu, placerat eget, venenatis a, magna."}, 
  { "weight": 13, "message": "volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor"}, 
  { "weight": 11, "message": "orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras"}, 
  { "weight": 6, "message": "ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices,"}, 
  { "weight": 8, "message": "natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a"}, 
  { "weight": 8, "message": "turpis egestas. Fusce aliquet magna a neque. Nullam ut nisi"}, 
  { "weight": 14, "message": "at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare"}, 
  { "weight": 15, "message": "mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus"}, 
  { "weight": 12, "message": "dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat"}, 
  { "weight": 7, "message": "aliquam adipiscing lacus. Ut nec urna et arcu imperdiet ullamcorper. Duis at lacus."}, 
  { "weight": 4, "message": "lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam"}, 
  { "weight": 1, "message": "consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus non lorem"}, 
  { "weight": 4, "message": "Praesent eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero"}, 
  { "weight": 5, "message": "Cras eget nisi dictum augue malesuada malesuada. Integer id magna"}, 
  { "weight": 14, "message": "vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis"}, 
  { "weight": 3, "message": "mi, ac mattis velit justo nec ante. Maecenas mi felis, adipiscing fringilla, porttitor"}, 
  { "weight": 8, "message": "Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae semper egestas, urna justo"}, 
  { "weight": 0, "message": "urna. Ut tincidunt vehicula risus. Nulla eget metus eu erat semper rutrum. Fusce"}, 
  { "weight": 15, "message": "Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse"}, 
  { "weight": 11, "message": "hendrerit consectetuer, cursus et, magna. Praesent interdum ligula eu enim. Etiam imperdiet"}, 
  { "weight": 15, "message": "imperdiet ullamcorper. Duis at lacus. Quisque purus sapien, gravida non,"}, 
  { "weight": 11, "message": "Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo"}, 
  { "weight": 4, "message": "felis eget varius ultrices, mauris ipsum porta elit, a feugiat"}, 
  { "weight": 10, "message": "ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu"}, 
  { "weight": 4, "message": "vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet"}, 
  { "weight": 15, "message": "Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque"}, 
  { "weight": 8, "message": "sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel"}, 
  { "weight": 7, "message": "metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer"}, 
  { "weight": 10, "message": "eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum"}, 
  { "weight": 3, "message": "sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac risus."}, 
  { "weight": 0, "message": "porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor"}, 
  { "weight": 1, "message": "sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh"}, 
  { "weight": 10, "message": "tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus."}, 
  { "weight": 0, "message": "velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada fringilla"}, 
  { "weight": 7, "message": "laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus"}, 
  { "weight": 6, "message": "iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend"}, 
  { "weight": 13, "message": "egestas rhoncus. Proin nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras"}, 
  { "weight": 6, "message": "ac mi eleifend egestas. Sed pharetra, felis eget varius ultrices,"}, 
  { "weight": 10, "message": "Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget"}, 
  { "weight": 13, "message": "mauris erat eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin dolor. Nulla semper tellus"}, 
  { "weight": 5, "message": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam auctor, velit eget laoreet posuere,"}, 
  { "weight": 6, "message": "sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet"}, 
  { "weight": 11, "message": "est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut, nulla."}, 
  { "weight": 5, "message": "lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec luctus aliquet odio. Etiam ligula"}, 
  { "weight": 8, "message": "libero lacus, varius et, euismod et, commodo at, libero. Morbi accumsan laoreet ipsum. Curabitur"},
  { "weight": 5, "message": "faucibus ut, nulla. Cras eu tellus eu augue porttitor interdum. Sed auctor odio a" } 
]